import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import styles from '../styles/Home.module.css';

export default function Home() {
  const handleOnClick = () => {
    console.log('Hello');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner buttonText='View Store Nearby' handleOnClick={handleOnClick} />
        <div className={styles.heroImage}>
          <Image
            src={'/static/hero-image.png'}
            width={700}
            height={400}
            alt=''
          />
        </div>
      </main>
    </div>
  );
}
